//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFApplicationDBEntityFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteProducts
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Product { get; set; }

        public FavoriteProducts()
        {

        }

        public FavoriteProducts(int idUser, int idProduct)
        {
            Id_User = idUser;
            Id_Product = idProduct;
        }

    }
}
